nt4f04uNd/sweyer

lib/constants/themes.dart, lib/localization/arb/intl_en.arb, lib/localization/arb/intl_ru.arb, lib/logic/prefs.dart, lib/logic/theme.dart, lib/routes/home_route/tabs_route.dart, lib/routes/routes.dart, lib/routes/settings_route/general_settings.dart, lib/routes/settings_route/settings_route.dart
This add back the general settings page and adds a new toggle setting to configure whether the shows the confirmation toast on exit.
I personally prefer that the app would just exit, as it is designed to run in the background anyways. Therefore I would like to have an option to toggle this behavior.
=> Allow to configure whether to show a confirmation toast on exit

lib/routes/home_route/search_route.dart
This is a missing padding on the right side of the ContentChip list that is used in the search route. The problem was visible on devices with smaller screen sizes.
I manually changed the translation to make it visible for the gifs, look at the right side:
| Before | After |
|--------|-------|
| ![Search result ContentChip list - Before](https://user-images.githubusercontent.com/6966049/167123082-b5e0f514-d2e8-4857-9a24-9a4104fe90fe.gif) | ![Search result ContentChip list - After](https://user-images.githubusercontent.com/6966049/167123096-95aa7923-0d30-4094-bc45-0dfb3b934629.gif) |
=> Add missing padding on the right of the ContentChip list

.github/workflows/sweyer.yml, .gitignore, CONTRIBUTING.md, codecov.yml
I think it would be nice be able to see code coverage online with [codecov](https://about.codecov.io). The only thing left to do for this to work is to create an account named `nt4f04uNd` with codecov and create a projecte named `sweyer`. Uploading coverage information should just work after that. There is no need to add a token to GitHub for public projects.
When the first coverage is uploaded we should check if we need the [dart-full-coverage action](https://github.com/marketplace/actions/dart-full-coverage). It sounds like by default files not loaded during the test don't count towards the coverage result? We'll have to see if that's true.
=> Integrate codecov

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/enhancement.yml
This adds two issue templates, which should help in writing issues and also automatically label the issue.
This is how it will look:
Notice that there is still an option to create a raw issue, if the templates don't fit. (The edit template options is only visible for admins.)
* Bug report:
* Enhancement request:
=> Add issue templates

codecov.yml, lib/logic/player/music_player.dart, test/routes/player_route_test.dart
This was enabled by default, now the two codecov status checks will always succeed.
This also fixes one source of unstable coverage, the `AudioHandler` wasn't properly re-initialized between tests. Let's see if that was the only source of coverage instability.
=> Don't fail the CI if coverage decreases

lib/routes/home_route/home_route.dart, lib/routes/routes.dart, test/routes/player_route_test.dart
Fixes #42 by adding an additional `RouterDelegateProvider` higher up in the widget tree so the `PlayerRoute` is able to access the `HomeRouter`.
The `HomeRouter.of(context)` call in `showSongsSearch` can now find the `RouterDelegateProvider`.
=> Fix opening the search page from a search query

README.md
I think it would be good for everyone who's stumbling across this repo in search of a music player to have a quick link to the Google Play store.
This is how it looks:
=> Add a link to the Google Play store entry to the README

lib/widgets/selection.dart
This changes the emerge animation of some buttons to emerge from the right. This looks better in my opinion, because it aligns with the movement of adjacent buttons:
| Current | After |
|----------|------|
| ![Search Selection and Delete Button Behaviour](https://user-images.githubusercontent.com/6966049/169668215-30f68cc1-3f02-4c33-b700-3c4a950a60a9.gif) | ![New select All button animation](https://user-images.githubusercontent.com/6966049/174872511-f2ebe791-b48d-4e77-b8ac-26e4390e7fd0.gif) |
| ![Emerge animations - Before](https://user-images.githubusercontent.com/6966049/174877519-1769e9a6-33cd-44de-a471-943e51930e10.gif) | ![Emerge animations - After](https://user-images.githubusercontent.com/6966049/174877543-64e6bc1a-5b86-49ba-85e0-193d7f341b4b.gif) |
Sorry, it's a bit hard to see, …
=> Emerge buttons from the right

.editorconfig, .gitignore, .idea/codeStyles/Project.xml, .idea/codeStyles/codeStyleConfig.xml, CONTRIBUTING.md, lib/routes/home_route/home_route.dart
This adds configuration for JetBrains editors and other editors respecting `.editorconfig` files to use the `120` character line length rule introduced in #61.
=> Add editor configurations for our formatting line length

lib/routes/home_route/artist_route.dart, lib/routes/home_route/home_route.dart, lib/routes/home_route/persistent_queue_route.dart, lib/routes/home_route/player_route.dart, lib/routes/routes.dart, lib/widgets/artist.dart, lib/widgets/bottom_track_panel.dart, lib/widgets/content_list_view/content_list_view.dart, lib/widgets/content_list_view/content_tile.dart, lib/widgets/content_list_view/in_list_action.dart, lib/widgets/content_list_view/song_tile.dart, lib/widgets/scrollbar.dart, lib/widgets/selection.dart, test/routes/home_route_test.dart
This fixes the layout issues seen when the system font size is increased. The `math.max` makes sure that the `kSongTileHeight` doesn't get too small. This is not the most elegant solution, since it requires us to pass the `textScaleFactor` around a lot, let me know if you find a better solution. Fixes #66.
| Largest font | Smallest font |
|--------------|----------------|
| ![Largest font](https://user-images.githubusercontent.com/6966049/174413100-aa95cd41-14fd-4e37-b3bc-595635dd2e1c.png) | ![Smallest font](https://user-images.githubusercontent.com/6966049/174413106-e6076b7b-a03f-4a8a-b1e4-f3d735f1e169.png) |
=> Fix layout issues caused by not accounting for the textScaleFactor

CHANGELOG.md, android/app/src/main/AndroidManifest.xml, lib/logic/device_info.dart, lib/logic/permissions.dart, pubspec.yaml, test/fakes/fake_just_audio.dart, test/golden/routes_golden_test.dart, test/logic/player/favorites_test.dart, test/observer/permissions.dart, test/routes/home_route_test.dart, test/routes/player_route_test.dart, test/routes/tabs_route_test.dart, test/test.dart
On Android 13, `READ_EXTERNAL_STORAGE` has been split into more [granular permissions](https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions), like `READ_MEDIA_AUDIO`. We need to request this permission to be able to query music from the content provider service. Fixes #83.
The `READ_MEDIA_AUDIO` will automatically be granted when requested if `READ_EXTERNAL_STORAGE` was previously granted.
=> Request the READ_MEDIA_AUDIO permission

lib/routes/home_route/persistent_queue_route.dart, lib/routes/home_route/player_route.dart, lib/routes/selection_route.dart, lib/widgets/selection.dart, sweyer_plugin/android/src/main/java/com/nt4f04und/sweyer/sweyer_plugin/SweyerPlugin.java, sweyer_plugin/lib/sweyer_plugin.dart, test/fakes/fake_sweyer_plugin_platform.dart, test/routes/selection_route_test.dart
This was originally fixed by #50, but seems to have regressed since then, probably due to a flutter update.
Looks like the dependency on `settingsOpened` was no longer registered in the `initState` function. We work around that by using a `StatefulBuilder`.
It is a bit weird that the goldens on CI did not pick this up in #85, they were showing the button consistently locally.
To make sure this doesn't regress in the future, I also added some tests for the selection route.
*This depends on and includes changes from #89 and will be kept as a draft until it is merged.*
=> Fix settings button visible on insertion settings page

lib/logic/player/content.dart, lib/logic/player/music_player.dart, lib/widgets/show_functions.dart, sweyer_plugin/lib/sweyer_plugin_method_channel.dart
This fixes a few problem that would cause the app to get stuck on the splash screen, when there was an error during startup.
I think it is a better user experience when we continue and show the app UI, even though some content might be missing because of the exception.
*This depends on and includes changes from #89 and will be kept as a draft until it is merged.*
=> Improve startup robustness

.github/workflows/build_and_test/action.yml, .github/workflows/build_executables.yml, .github/workflows/sweyer.yml, .github/workflows/sweyer_release.yml, .github/workflows/test/action.yml, .github/workflows/update_goldens.yml
It would be good if CI would notify us if a change would break building the APK.
Unfortunately this increases our CI runtime from ~2min 30sec to ~4min 30sec. I already added a cache for Gradle, which helped a ton, but caching the Android SDK is not helping.
=> Add CI job to build APK

lib/routes/home_route/search_route.dart
I guess `Scrollable.of` was nullable before Flutter switched to sound null safety. `Scrollable.maybeOf` does the same thing but doesn't error when no scrollable was found, which is what we want here.
Fixes #128.
=> Fix null exception when filtering while searching

lib/routes/home_route/player_route.dart
When the artist name of a song is very large, if filles the entire width of the screen right up to the border.
This feels a bit weird and unpolished, so I added a `20px` padding (The song title has `30px` padding).
| Before | After |
| ------- | ------ |
| ![Artist text - before](https://github.com/user-attachments/assets/9a7410d6-46c1-4b5d-afc5-8170f2f643e1) | ![Artist text - after](https://github.com/user-attachments/assets/3be5ca7c-a1c1-4da7-9f9a-84b4eda40d80) |
=> Add some horizontal padding to the artist name on the player screen

sweyer_plugin/android/src/main/kotlin/com/nt4f04und/sweyer/sweyer_plugin/SweyerPlugin.kt
The original Java code also had the wrong type, but Kotlin is much more strict so this became a runtime error when we switched to Kotlin.
<details><summary>This fixes the <code>MethodChannelSweyerPlugin.setSongsFavorite</code> crash captured in Crashlytics</summary>
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PUa: setSongsFavorite failed
Caused by:
PlatformException(UNEXPECTED_ERROR, java.lang.Integer cannot be cast to java.util.ArrayList, java.lang.ClassCastException: java.lang.Integer cannot be cast to java.util.ArrayList
at b5.r0.F(Unknown Source:377)
at z5.k$a.a(Unknown Source:17)
at n5.c.l(Unknown Source:18)
at n5.c.m(Unknown Source:40)
at n5.c.i(Unknown Source:0)
at n5.b.run(Unknown Source:12)
at android.os.Handler.handleCallback(Handler.java:938) …
```
=> Fix marking songs as favourite with the Android system

.github/workflows/build_executables.yml, .github/workflows/tests.yml
1. Rename workflows for more clarity
2. Run builds only on push to main branches (this removes double builds in PRs)
3. Enable executable builds on push to main branches
=> Adjust worflow runs

lib/logic/models/selection_entry.dart, lib/logic/player/content.dart, lib/widgets/selection.dart
Fixes https://github.com/nt4f04uNd/sweyer/issues/98
Problem was on this line
https://github.com/nt4f04uNd/sweyer/blob/fix/98/playlist-deselect-all/lib/routes/home_route/search_route.dart#L619
Also, here this code couldn't pick up the proper `runtimeType`
I refactored both places for double-bulletproof + other place where we were checking runtimeType, instead of `contentType`
Opened an issue to remove all usages of runtimeType
https://github.com/nt4f04uNd/sweyer/issues/137
=> Fix deselect all

.github/workflows/deploy_google_play/action.yml, .github/workflows/sweyer_release.yml, .github/workflows/tests.yml, .github/workflows/update_goldens.yml
This updates our CI dependencies. I read through the change logs and made sure that there are no breaking changes for us.
There is one exception:
`codecov/codecov-action@v4` removes tokenless uploads of coverage information. This means that we need to make sure that we have [configured our Codecov token in the GitHub repository settings as described in the documentation](https://docs.codecov.com/docs/adding-the-codecov-token#github-actions). I don't have access to these settings so only you can do that.
Hopefully the update will fix the Codecov upload failures we've seen on recent CI runs like [here](https://github.com/nt4f04uNd/sweyer/actions/runs/10121497714/job/27992507895#step:4:33).
=> Update all GitHub actions dependencies

lib/logic/models/playlist.dart
Use the creation date if no modification date is present.
This fixes the following error observed on Crashlytics ([[1]](https://console.firebase.google.com/u/2/project/sweyer-def42/crashlytics/app/android:com.nt4f04und.sweyer/issues/d1875b57ccacd08b9b36a5fe2c6ec794?time=last-ninety-days&sessionEventKey=6692686C012B000167ECB8B434C003B9_1969530388087311267), maybe also [[2]](https://console.firebase.google.com/u/2/project/sweyer-def42/crashlytics/app/android:com.nt4f04und.sweyer/issues/f4716b11a5257ee44c8995acc25e7e3d?time=last-ninety-days&sessionEventKey=666CE8C8017A00013B5A7B3F3CA8932E_1958977251308973358), [[3]](https://console.firebase.google.com/u/2/project/sweyer-def42/crashlytics/app/android:com.nt4f04und.sweyer/issues/afe37557daeeb231ef7c67a9eeb42fe2?time=last-ninety-days&sessionEven …
=> Don't error when a playlist has no modification date

sweyer_plugin/android/src/main/kotlin/com/nt4f04und/sweyer/sweyer_plugin/handlers/FetchHandler.kt
This is an attempt to fix the `java.lang.IllegalArgumentException: Volume external_primary not found` that we see on Crashlytics ([[1]](https://console.firebase.google.com/u/2/project/sweyer-def42/crashlytics/app/android:com.nt4f04und.sweyer/issues/612523973ce5c75b4258b250bbace33e?time=last-ninety-days&sessionEventKey=6679036E025E0001146F2EE12BAD35D5_1962382447577852706), [[2]](https://console.firebase.google.com/u/2/project/sweyer-def42/crashlytics/app/android:com.nt4f04und.sweyer/issues/a59942b3b39bda908c06adaaf545b72d?time=last-ninety-days&sessionEventKey=6679036E025E0001146F2EE12BAD35D5_1962382447577852708), [[3]](https://console.firebase.google.com/u/2/project/sweyer-def42/crashlytics/app/android:com.nt4f04und.sweyer/issues/b9f977f35adceab9fa61f6d2ff5dc366?time=last-ninety-days&sessio …
=> Use getContentUri on newer Android versions

lib/widgets/content_list_view/persistent_queue_tile.dart, pubspec.lock, pubspec.yaml, test/routes/selection_route_test.dart
*Depends on #130.*
With the update of Flutter came an update to Dart 3 wich introduces records (aka tuples), so we don't need the dependency anymore.
=> Remove tuple dependency

lib/logic/models/album.dart, lib/logic/models/genre.dart, lib/logic/models/playlist.dart, lib/logic/models/song.dart
Similar to #145, but for other fields where we can handle null in a simple way.
This makes the content scanning more robust and hopefully prevents errors like the one linked in #145.
Woks towards the third checkmark on #127.
=> Accept null for more content fields

lib/logic/models/song.dart, lib/logic/player/favorites.dart
While adding tests to work towards #127, I noticed that we would crash if `isFavoriteInMediaStore` was `null`. We haven't seen this on Crashlytics yet, but this can definitely happen on older (pre `R`, API level `30`) devices.
=> If the media store favourite state is unknown, treat it as no favourite

lib/logic/player/playback.dart, lib/routes/settings_route/theme_settings.dart, test/routes/home_route_test.dart
The user can change settings before granting permissions to the media. In this state we don't fully initialize the audio player, which caused a crash that was captured by Crashlytics ([[1]](https://console.firebase.google.com/u/2/project/sweyer-def42/crashlytics/app/android:com.nt4f04und.sweyer/issues/e1062f968ba29597bf7c151f0113590f?time=last-ninety-days&sessionEventKey=66806057037500011F3F73AEE12731E5_1964456254375290935), maybe also [[2]](https://console.firebase.google.com/u/2/project/sweyer-def42/crashlytics/app/android:com.nt4f04und.sweyer/issues/2c370cc8ce03b3ee6f49bd7e6fc8a846?time=last-ninety-days&sessionEventKey=666A34A0023500012288FB1F4F235DDF_1958214607951902040)).
<details><summary>Stacktrace</summary>
```
Non-fatal Exception: …
```
=> Fix error when changing the app color before granting permissions

lib/logic/models/playlist.dart, lib/logic/models/sort.dart, lib/utils/compare.dart, lib/utils/utils.dart, test/logic/models/sort_test.dart
Instead of falling back to the `dateAdded`, we now just allow the modification date of a playlist to be null. This is only really relevant during sorting, where we sort playlists with a null modification date towards the end (regardless whether we sort ascending or descending) (as discussed in https://github.com/nt4f04uNd/sweyer/pull/152#discussion_r1730453903). Fixes #157.
=> Allow playlist modification date to be nullable

.github/dependabot.yml
This will allow Dependabot to update the `/android/Gemfile.lock` file.
We have some security vulnarabillity alerts that will hopefully be fixed by this.
=> Configure Dependabot to update the fastlane gemfile

android/Gemfile
Unfortunately dependabot failed to parse the `/androif/Gemfile`, which was added in #179.
This approach should not change the behaviour of the Gemfile, and seems to work for https://github.com/WFCD/navis/blob/master/android/Gemfile.
=> Simplify the Gemfile so dependabot can parse it correctly

lib/logic/models/album.dart, lib/logic/models/artist.dart, lib/logic/models/content.dart, lib/logic/models/genre.dart, lib/logic/models/playlist.dart, lib/logic/models/song.dart, sweyer_plugin/lib/sweyer_plugin.dart, test/fakes/fake_firebase.dart, test/fakes/fake_sweyer_plugin_platform.dart, test/fakes/fakes.dart, test/logic/models/content_test.dart, test/observer/crashlytics.dart, test/observer/observer.dart, test/test.dart
*This includes #145 and is based on top of #148.*
This makes content scanning more robust and prevents failing the entire content search because one item fails by catching exceptions on an item level and reporting them, which implements the first checkbox on #127.
I think it is valuable to report these as non-fatal errors, so we can see if we are too strict and need to make a content attribute nullable.
=> Improve content scanning

.fvmrc, .github/workflows/build_executables.yml, .github/workflows/deploy_google_play/action.yml, .github/workflows/test/action.yml, android/app/build.gradle, android/app/src/main/kotlin/com/nt4f04und/sweyer/MusicPlayerAppWidget.kt, android/gradle/wrapper/gradle-wrapper.properties, android/settings.gradle, lib/localization/arb/intl_de.arb, lib/localization/arb/intl_en.arb, lib/localization/arb/intl_ru.arb, lib/localization/arb/intl_tr.arb, lib/logic/player/music_player.dart, lib/routes/home_route/player_route.dart, lib/widgets/show_functions.dart, pubspec.lock, pubspec.yaml, sweyer_plugin/android/build.gradle, test/fakes/fake_just_audio.dart, test/logic/player/music_player_test.dart
Update to the newest Flutter version. This also updates all dependencies, but does not update any major versions, to keep this MR short (except `audio_service`). This also does not fix the new warnings. During build, there is a new warning:
```
Synthetic package output (package:flutter_gen) is deprecated: https://flutter.dev/to/flutter-gen-deprecation. In a future release, synthetic-package will default to `false`
and will later be removed entirely.
```
I'll address this in a future PR.
This PR depends on https://github.com/nt4f04uNd/nt4f04unds_widgets/pull/14, but is already ready for review.
=> Update to Flutter 3.29.2

.github/workflows/test/action.yml, .gitignore, l10n.yaml, lib/localization/localization.dart, pubspec.yaml, test/test.dart
This fixes the following warning on every build:
```
Synthetic package output (package:flutter_gen) is deprecated: https://flutter.dev/to/flutter-gen-deprecation. In a future release, synthetic-package will default to `false` and will later be removed entirely.
```
I've followed the [migration guide](https://docs.flutter.dev/release/breaking-changes/flutter-generate-i10n-source#migration-guide), now the sources are generated into `lib/localization/generated` instead of a synthetic package.
=> Don't use a synthetic generated package for localizations

.github/workflows/test/action.yml, pubspec.yaml
See https://github.com/nt4f04uNd/sweyer/pull/316#issuecomment-2799912277. Without the `generate: true`, flutter only generates them on `flutter build`. I thought in #316 that we need to get rid of this  setting to fix the warning, but it looks like we want it and it's ok to have it as long as we are not using the synthetic package.
=> Let flutter automatically generate localization files on `pub get`

pubspec.lock, pubspec.yaml, sweyer_plugin/example/pubspec.lock
Based on #318, updates all dependencies to new major versions (except `rxdart`, see #270).
To be merged after #318.
=> Update dependencies after updating the project template
